export const CustomerActionTypes = {
    CHANGE_VALUE: 'CHANGE_VALUE',
    CHANGE_VALUE_ECOMMERCIAL: 'CHANGE_VALUE_ECOMMERCIAL',
    CHANGE_VALUE_SHIPPING: 'CHANGE_VALUE_SHIPPING',
    ADD_EMAIL: 'ADD_EMAIL',
    ADD_ECOMMERCIAL: 'ADD_ECOMMERCIAL',
    ADD_SHIPPINGACCOUNT: 'ADD_SHIPPINGACCOUNT',
    DELETE_DATA: 'DELETE_DATA',
    CLEAR: 'CLEAR'
}