export const ModelActionTypes = {
    ASSIGNRESPONSE: 'ASSIGNRESPONSE',
    CHANGE_VALUE: 'CHANGE_VALUE',
    CLEAR: 'CLEAR',
    ASSIGNINITMODEL: 'ASSIGNINITMODEL',
    CLEAR_RESPONSE: 'CLEAR_RESPONSE'
}